# fly.toml file generated for dawn-firefly-6294 on 2022-10-16T22:09:40+02:00

app = "dawn-firefly-6294"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 443
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 3025
  protocol = "tcp"

  [[services.ports]]
    port = 3025

[[services]]
  internal_port = 3023
  protocol = "tcp"

  [[services.ports]]
    port = 3023

[[services]]
  internal_port = 3024
  protocol = "tcp"

  [[services.ports]]
    port = 3024